
const ActionTypes = {
    FETCH_ALL_PRODUCTS:"FETCH_ALL_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    DELETE_SELECTED_PRODUCT:"DELETE_SELECTED_PRODUCT",
    SET_PRODUCTS:"SET_PRODUCTS"
}

export default ActionTypes;